# Generated by Django 3.1.4 on 2021-11-26 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='student',
            name='lasrname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studentid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lasrname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 5, 26, 28, 766727, tzinfo=utc)),
        ),
    ]
