# Generated by Django 3.1.4 on 2021-11-26 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20211126_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lasrname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lasrname',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 5, 32, 23, 240278, tzinfo=utc)),
        ),
    ]
