# Generated by Django 3.1.4 on 2021-11-26 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20211126_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.student'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 6, 30, 17, 85727, tzinfo=utc)),
        ),
    ]
